# Move the directory to the second line
format = '$all$directory$character'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

[git_branch]
# Customize the format to show only the branch name
format = "🔧 [$branch](bold yellow) * "
symbol = ""  # Remove the branch symbol

[directory]
truncation_length = 4
truncation_symbol = "…/"
format = "[$path](bold blue)[$read_only](red) "

[git_status]
disabled = false  # Disable the git_status module

[nodejs]
disabled = true
